# train_agent.py — trains PPO on FocusEnv using simulated sessions
import os
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from env import FocusEnv
import matplotlib.pyplot as plt
import numpy as np

SIM_NAME = "session1.csv"  # generated by simulator.py

def train(total_timesteps=200_000, save_path=None):
    env = DummyVecEnv([lambda: FocusEnv(sim_csv=SIM_NAME)])
    model = PPO("MlpPolicy", env, verbose=1, tensorboard_log="./tb_logs/")
    model.learn(total_timesteps=total_timesteps)
    if not save_path:
        save_path = os.path.join(os.path.dirname(__file__), "..", "models", "focus_agent")
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    model.save(save_path)
    print("Saved model to", save_path)
    return model

    if __name__ == "__main__":
        model = train(100_000)
